name: DeployProdServer

on:
  workflow_dispatch:

env:
  IMAGE_NAME: devupbet/server:${{ github.ref_name }}

jobs:

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Update kubeconfig
        id: kubeconfig
        run: |
          aws eks update-kubeconfig --region sa-east-1 --name upbet2025-arm-cluster
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/server-deployment server=${{ env.IMAGE_NAME }}
          kubectl rollout status deployment/server-deployment

      - name: Restart server
        run: |
          kubectl rollout restart deployment/server-deployment
